GEMINI_API_KEY="AIzaSyDNO8WW0cKbmv8J1yLLc6Klwv4SNeZGcTI"
HUBSPOT_TOKEN="pat-ap1-5a3fb4e0-b620-47a7-9ddf-83d283be3c92"
CLOCKIFY_API_KEY="Yzk1OWUwNjEtYWYxMy00OGRiLTk4OTctNTI3MGU5MDFmNzJm"
DATABASE_URL="postgresql://postgres.rqgghtuxcurymngvwofm:TestVallocate2026@aws-1-ap-southeast2.pooler.supabase.com:6543/postgres"
